In [5]:
import numpy as np
import pandas as pd
import random
from hmmlearn import hmm
import matplotlib.pyplot as plt

In [6]:
random.seed(200256758)

In [7]:
P = np.zeros(shape=(4,4))
for i in range(4):
    for j in range(4):
        rnum=random.random()
        P[i][j]=rnum
    P[i]=P[i]/sum(P[i])
P

array([[0.19547493, 0.13757054, 0.29319991, 0.37375462],
       [0.04133207, 0.33883134, 0.29073149, 0.3291051 ],
       [0.27688667, 0.26228274, 0.25067505, 0.21015553],
       [0.23890892, 0.24938778, 0.22122013, 0.29048318]])

In [8]:
B = np.zeros(shape=(4,3))
for i in range(4):
    for j in range(3):
        rnum=random.random()
        B[i][j]=rnum
    B[i]=B[i]/sum(B[i])
B

array([[0.14493102, 0.28696169, 0.56810729],
       [0.0595772 , 0.5480175 , 0.39240531],
       [0.17631078, 0.42892038, 0.39476884],
       [0.33184461, 0.30245334, 0.36570205]])

In [9]:
Q = np.zeros(1000, dtype = int)
O = np.zeros(1000, dtype = int)    

In [10]:
for i in range(1000):
    if i==0:
        Q[i]=1
    else:
        rnum=random.random()
        #print ("Q ", rnum)
        if rnum<=P[Q[i-1]-1][0]: Q[i]=1
        elif rnum<=(P[Q[i-1]-1][0] + P[Q[i-1]-1][1]): Q[i]=2
        elif rnum<=(P[Q[i-1]-1][0] + P[Q[i-1]-1][1] + P[Q[i-1]-1][2]): Q[i]=3
        else: Q[i]=4
            
            
    rnum=random.random()
    #print ("O ", rnum)
    if rnum<=B[Q[i]-1][0]: O[i]=1
    elif rnum<=(B[Q[i]-1][0] + B[Q[i]-1][1]): O[i]=2
    else: O[i]=3
            
print (Q[:10],O[:10])                    

[1 3 3 1 3 3 3 4 1 4] [2 3 3 3 2 3 2 1 3 3]


In [11]:
len(Q), len(O)

(1000, 1000)