In [2]:
import numpy as np
import pandas as pd
import random

In [3]:
random.seed(200256758)

In [4]:
P = np.zeros(shape=(4,4))
for i in range(4):
    for j in range(4):
        rnum=random.random()
        P[i][j]=rnum
    P[i]=P[i]/sum(P[i])
P

array([[0.19547493, 0.13757054, 0.29319991, 0.37375462],
       [0.04133207, 0.33883134, 0.29073149, 0.3291051 ],
       [0.27688667, 0.26228274, 0.25067505, 0.21015553],
       [0.23890892, 0.24938778, 0.22122013, 0.29048318]])

In [5]:
B = np.zeros(shape=(4,3))
for i in range(4):
    for j in range(3):
        rnum=random.random()
        B[i][j]=rnum
    B[i]=B[i]/sum(B[i])
B

array([[0.14493102, 0.28696169, 0.56810729],
       [0.0595772 , 0.5480175 , 0.39240531],
       [0.17631078, 0.42892038, 0.39476884],
       [0.33184461, 0.30245334, 0.36570205]])

In [6]:
pi=np.array([1,0,0,0])
seq=np.array([1,2,3,3,1,2,3,3,1,2,3,3])
seq=seq-1
states=('1','2','3','4')
observations =('1','2','3')

In [18]:
def init(obs_seq):
    T = len(obs_seq)
    N = P.shape[0]
    return (T,N)

In [19]:
def initialize_fwd(obs_seq):
    T,N=init(obs_seq)
    alpha = np.zeros((T, N))
    alpha[0] = pi*B[:,obs_seq[0]]
    return (T, alpha)

In [20]:
def initialize_bwd(obs_seq):
    T,N=init(obs_seq)
    beta = np.zeros((N,T))
    beta[:,-1:] = 1
    return (T,N,beta)

In [25]:
def forward(obs_seq):        
        T,alpha=initialize_fwd(obs_seq)
        for t in range(1, T,1):
            alpha[t] = alpha[t-1].dot(P) * B[:, obs_seq[t]]
        return alpha

In [37]:
def backward(obs_seq):
        T,N, beta=initialize_bwd(obs_seq)        
        for t in range(T-2,-1,-1):
            for n in range(N):
                beta[n,t] = np.sum(beta[:,t+1] * P[n,:] * B[:, obs_seq[t+1]])

        return beta

In [38]:
alpha = forward(seq)
beta  = backward(seq)
prob=np.multiply(alpha,beta.T)
prob

array([[1.54184678e-06, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.34819886e-07, 2.90747343e-07, 5.39921202e-07, 4.76358352e-07],
       [4.24252763e-07, 3.32621788e-07, 3.92471415e-07, 3.92500818e-07],
       [4.44790990e-07, 3.50127014e-07, 3.46338816e-07, 4.00589964e-07],
       [2.19518219e-07, 1.27963791e-07, 3.82924583e-07, 8.11440191e-07],
       [2.62234305e-07, 4.94673417e-07, 4.33725025e-07, 3.51214038e-07],
       [3.65690708e-07, 3.49967664e-07, 4.11175702e-07, 4.15012709e-07],
       [4.43826139e-07, 3.58014050e-07, 3.44264845e-07, 3.95741751e-07],
       [2.18314735e-07, 1.28306200e-07, 3.83211301e-07, 8.12014549e-07],
       [2.61053457e-07, 4.95227804e-07, 4.34254700e-07, 3.51310823e-07],
       [3.66636534e-07, 3.60789178e-07, 4.04417796e-07, 4.10003276e-07],
       [3.95338900e-07, 3.59310752e-07, 3.83013172e-07, 4.04183960e-07]])

In [39]:
np.sum(prob, axis=1)

array([1.54184678e-06, 1.54184678e-06, 1.54184678e-06, 1.54184678e-06,
       1.54184678e-06, 1.54184678e-06, 1.54184678e-06, 1.54184678e-06,
       1.54184678e-06, 1.54184678e-06, 1.54184678e-06, 1.54184678e-06])