In [38]:
import numpy as np
import pandas as pd
import random
from hmmlearn import hmm


In [127]:
random.seed(200256758)

In [137]:
P = np.zeros(shape=(4,4))
for i in range(4):
    for j in range(4):
        rnum=random.random()
        P[i][j]=rnum
    P[i]=P[i]/sum(P[i])
P

array([[0.15006412, 0.21089082, 0.33533053, 0.30371453],
       [0.36806576, 0.06741943, 0.3217626 , 0.24275222],
       [0.15534356, 0.2861196 , 0.29057436, 0.26796247],
       [0.21117287, 0.58982526, 0.14828762, 0.05071426]])

In [138]:
B = np.zeros(shape=(4,3))
for i in range(4):
    for j in range(3):
        rnum=random.random()
        B[i][j]=rnum
    B[i]=B[i]/sum(B[i])
B

array([[0.29661724, 0.34664082, 0.35674193],
       [0.46777237, 0.30896662, 0.223261  ],
       [0.33736357, 0.18655961, 0.47607682],
       [0.36383816, 0.24059621, 0.39556562]])

In [139]:
pi=np.array([1,0,0,0])
seq=np.array([1,2,3,3,1,2,3,3,1,2,3,3])
seq=seq-1
states=('1','2','3','4')
observations =('1','2','3')

In [140]:
def init(obs_seq):
    T = len(obs_seq)
    N = P.shape[0] 
    delta = np.zeros((T, N))        
    psi = np.zeros((T, N))  
    return (T,N,psi,delta)


In [141]:
def backtrack(T,delta, psi):
     # backtrack
        states = np.zeros(T, dtype=np.int32)
        states[T-1] = np.argmax(delta[T-1])
        for t in range(T-2, -1, -1):
            states[t] = psi[t+1, states[t+1]]
        return states

In [142]:
def viterbi(obs_seq):
        T,N,psi,delta = init(obs_seq)
        delta[0] = pi*B[:,obs_seq[0]]
        
        for t in range(1, T):
            for i in range(N):
                delta[t,i] = np.max(delta[t-1]*P[:,i]) * B[i, obs_seq[t]]
                psi[t,i] = np.argmax(delta[t-1]*P[:,i])

        res=backtrack(T, delta,psi)
        return res
       


In [143]:
obs_states=viterbi(seq)+1

In [144]:
obs_states

array([1, 2, 3, 4, 2, 1, 3, 4, 2, 1, 3, 3], dtype=int32)